# winlibs
version: 1.{build}
image: 
  - Visual Studio 2019
platform: 
  - x64
configuration: 
  - Release
cache:
  - C:\strawberry
  - C:\cache
install:
  - dir C:\cache || mkdir C:\cache
  - if not exist C:\strawberry choco install strawberryperl -y
  - set PATH=C:\strawberry\perl\bin;%PATH%
  - cd %APPVEYOR_BUILD_FOLDER%
  - perl -v
  - cmd: |
      if not exist C:\cache\nasm.zip appveyor DownloadFile "https://github.com/joedrago/nasm_mirror/raw/master/nasm-2.14.02-win64.zip" -FileName "C:\cache\nasm.zip"
      7z x C:\cache\nasm.zip
      move nasm-* NASM
      set PATH=%PATH%;%CD%\NASM
      nasm -v
build_script:
  - rd /s /q C:\OpenSSL-Win64
  - rd /s /q C:\OpenSSL-Win32
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"
  - set PLATFORM=x64
  - call build.bat
  # - call build2.bat
  # - call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars32.bat"
  # - set PLATFORM=x86
  # - call build.bat
  # - call build2.bat  
artifacts:
  - path: vendor
    name: winlibs
    type: zip
  - path: vendor2
    name: winlibs2
    type: zip
notifications: off
deploy: off