version: 1.{build}
image: 
  - Visual Studio 2019
  - Visual Studio 2017
  - Visual Studio 2015
  - Visual Studio 2013
platform: 
  - x64
  - x86
configuration: 
  - Release
  - Debug
build_script:
  - build_dep.bat
